#MYSQL
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/oauth
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
server:
  port: 8081
#H2
spring:
  datasource:
    url: jdbc:h2:file:~/data/h2/testdb;MODE=MySQL
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

spring.h2.console:
  enabled: true
  path: /h2-console

# »ç¿ë
security:
  user:
    name: user
    password: test

#logging:
#  level:
#    ROOT: DEBUG
