spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/java_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: scott
    password: tiger
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
        format_sql: true
    show-sql: true

  # https://github.com/settings/developers
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5504a3f326a7a88787cb
            client-secret: 43a2b6d994d3b6d42af887b992342d74da1a335d
